# Generated by Django 6.0.5 on 2026-05-21 23:02

import django.core.validators
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(editable=False, help_text='Numéro séquentiel unique généré automatiquement', max_length=50, unique=True, verbose_name='Numéro de facture')),
                ('client_name', models.CharField(max_length=200, verbose_name='Nom du client')),
                ('client_email', models.EmailField(blank=True, max_length=254, verbose_name='Email du client')),
                ('client_phone', models.CharField(blank=True, max_length=20, verbose_name='Téléphone du client')),
                ('client_address', models.TextField(blank=True, verbose_name='Adresse du client')),
                ('issue_date', models.DateField(default=django.utils.timezone.now, verbose_name="Date d'émission")),
                ('due_date', models.DateField(verbose_name="Date d'échéance")),
                ('payment_terms', models.CharField(choices=[('immediate', 'Paiement immédiat'), ('net_15', 'Net 15 jours'), ('net_30', 'Net 30 jours'), ('net_60', 'Net 60 jours'), ('net_90', 'Net 90 jours')], default='net_30', max_length=20, verbose_name='Conditions de paiement')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Sous-total HT')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux de TVA (%)')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant TVA')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant total TTC')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('sent', 'Envoyée'), ('paid', 'Payée'), ('overdue', 'En retard'), ('cancelled', 'Annulée')], default='draft', max_length=20, verbose_name='Statut')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi")),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de paiement')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'db_table': 'invoicing_invoice',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Description')),
                ('quantity', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Quantité')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prix unitaire HT')),
                ('tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Taux de TVA (%)')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Sous-total HT')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='Montant TVA')),
                ('total', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Total TTC')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Ligne de facture',
                'verbose_name_plural': 'Lignes de facture',
                'db_table': 'invoicing_invoice_item',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(default='INV', max_length=20, verbose_name='Préfixe')),
                ('current_number', models.PositiveIntegerField(default=1, verbose_name='Numéro actuel')),
                ('year', models.PositiveIntegerField(default=2026, verbose_name='Année')),
                ('reset_annually', models.BooleanField(default=True, verbose_name='Réinitialiser annuellement')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Séquence de facturation',
                'verbose_name_plural': 'Séquences de facturation',
                'db_table': 'invoicing_invoice_sequence',
            },
        ),
        migrations.CreateModel(
            name='TaxConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('18.00'), max_digits=5, verbose_name='Taux de TVA par défaut (%)')),
                ('tax_enabled', models.BooleanField(default=True, verbose_name='TVA activée')),
                ('tax_number', models.CharField(blank=True, max_length=50, verbose_name="Numéro d'identification fiscale")),
                ('tax_name', models.CharField(default='TVA', max_length=50, verbose_name='Nom de la taxe')),
                ('reduced_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taux réduit (%)')),
                ('exempt_tax_rate', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5, verbose_name='Taux exonéré (%)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuration fiscale',
                'verbose_name_plural': 'Configurations fiscales',
                'db_table': 'invoicing_tax_configuration',
            },
        ),
    ]
