# Generated by Django 6.0.5 on 2026-05-21 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('invoicing', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='Créée par'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='journal_entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice', to='accounting.journalentry', verbose_name='Écriture comptable'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoicing.invoice', verbose_name='Facture'),
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='revenue_account',
            field=models.ForeignKey(help_text='Compte de revenu OHADA pour cette ligne', on_delete=django.db.models.deletion.PROTECT, related_name='invoice_items', to='accounting.account', verbose_name='Compte de revenu'),
        ),
        migrations.AddField(
            model_name='invoicesequence',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_sequence', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='taxconfiguration',
            name='organization',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tax_configuration', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'status'], name='invoicing_i_organiz_180859_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['organization', 'invoice_number'], name='invoicing_i_organiz_2a8d7c_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['due_date'], name='invoicing_i_due_dat_92e42f_idx'),
        ),
        migrations.AddIndex(
            model_name='invoice',
            index=models.Index(fields=['status'], name='invoicing_i_status_2eeee5_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoicesequence',
            unique_together={('organization', 'year')},
        ),
    ]
