# Generated by Django 6.0.5 on 2026-05-22 10:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='ex: XOF, EUR, USD, GBP', max_length=3, unique=True, verbose_name='Code ISO 4217')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la devise')),
                ('symbol', models.CharField(help_text='ex: FCFA, €, $, £', max_length=5, verbose_name='Symbole')),
                ('decimal_places', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name='Nombre de décimales')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('is_default', models.BooleanField(default=False, help_text='Devise par défaut pour les nouvelles organisations', verbose_name='Devise par défaut')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name="Pays d'origine")),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Devise',
                'verbose_name_plural': 'Devises',
                'db_table': 'currencies_currency',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['code'], name='currencies__code_712bc0_idx'), models.Index(fields=['is_active'], name='currencies__is_acti_4f1b46_idx'), models.Index(fields=['is_default'], name='currencies__is_defa_735daa_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20, verbose_name='Solde')),
                ('base_currency_equivalent', models.DecimalField(decimal_places=10, default=Decimal('0.00'), max_digits=20, verbose_name='Équivalent en devise de base')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='Dernière mise à jour')),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='currencies.currency', verbose_name='Devise')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_balances', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Solde par devise',
                'verbose_name_plural': 'Soldes par devise',
                'db_table': 'currencies_currency_balance',
                'indexes': [models.Index(fields=['organization', 'currency'], name='currencies__organiz_a95656_idx'), models.Index(fields=['last_updated'], name='currencies__last_up_dddf3e_idx')],
                'unique_together': {('organization', 'currency')},
            },
        ),
        migrations.CreateModel(
            name='CurrencyConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_convert', models.BooleanField(default=True, help_text='Convertir automatiquement les montants dans la devise de base', verbose_name='Conversion automatique')),
                ('use_latest_rates', models.BooleanField(default=True, help_text='Utiliser les taux de change les plus récents', verbose_name='Utiliser les derniers taux')),
                ('rounding_precision', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(4)], verbose_name="Précision d'arrondi")),
                ('rounding_method', models.CharField(choices=[('half_up', 'Arrondi supérieur (0.5+)'), ('half_down', 'Arrondi inférieur (0.5+)'), ('up', 'Toujours supérieur'), ('down', 'Toujours inférieur')], default='half_up', max_length=20, verbose_name="Méthode d'arrondi")),
                ('max_rate_age_days', models.IntegerField(default=7, help_text='Alerte si les taux de change sont plus anciens que ce nombre de jours', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(365)], verbose_name='Âge maximum des taux (jours)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_currencies', models.ManyToManyField(blank=True, related_name='allowed_currency_configs', to='currencies.currency', verbose_name='Devises autorisées')),
                ('base_currency', models.ForeignKey(help_text="Devise principale pour l'organisation", on_delete=django.db.models.deletion.PROTECT, related_name='base_currency_configs', to='currencies.currency', verbose_name='Devise de base')),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_configuration', to='organizations.organization', verbose_name='Organisation')),
                ('reporting_currency', models.ForeignKey(help_text='Devise utilisée pour les rapports', on_delete=django.db.models.deletion.PROTECT, related_name='reporting_currency_configs', to='currencies.currency', verbose_name='Devise de reporting')),
            ],
            options={
                'verbose_name': 'Configuration de devises',
                'verbose_name_plural': 'Configurations de devises',
                'db_table': 'currencies_currency_configuration',
                'indexes': [models.Index(fields=['organization', 'base_currency'], name='currencies__organiz_ef6a60_idx'), models.Index(fields=['organization', 'reporting_currency'], name='currencies__organiz_fda777_idx')],
            },
        ),
        migrations.CreateModel(
            name='CurrencyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('invoice', 'Facture'), ('payment', 'Paiement'), ('expense', 'Dépense'), ('journal_entry', 'Écriture comptable'), ('other', 'Autre')], max_length=20, verbose_name='Type de transaction')),
                ('object_id', models.PositiveIntegerField(blank=True, null=True, verbose_name="ID de l'objet")),
                ('original_amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Montant original')),
                ('base_amount', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Montant en devise de base')),
                ('exchange_rate', models.DecimalField(decimal_places=10, max_digits=20, verbose_name='Taux de change utilisé')),
                ('rate_date', models.DateField(verbose_name='Date du taux')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('base_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='base_transactions', to='currencies.currency', verbose_name='Devise de base')),
                ('content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype', verbose_name='Type de contenu')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='currency_transactions', to='organizations.organization', verbose_name='Organisation')),
                ('original_currency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='original_transactions', to='currencies.currency', verbose_name='Devise originale')),
            ],
            options={
                'verbose_name': 'Transaction multi-devises',
                'verbose_name_plural': 'Transactions multi-devises',
                'db_table': 'currencies_currency_transaction',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'transaction_type'], name='currencies__organiz_1f3a4e_idx'), models.Index(fields=['original_currency', 'base_currency'], name='currencies__origina_c1e6a5_idx'), models.Index(fields=['rate_date'], name='currencies__rate_da_e15beb_idx'), models.Index(fields=['content_type', 'object_id'], name='currencies__content_dde3ee_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=10, help_text='1 unité de from_currency = rate unités de to_currency', max_digits=20, validators=[django.core.validators.MinValueValidator(Decimal('1E-10'))], verbose_name='Taux de change')),
                ('date', models.DateField(help_text="Date à laquelle ce taux s'applique", verbose_name='Date du taux')),
                ('source', models.CharField(blank=True, help_text='ex: BCEAO, ECB, manual', max_length=100, verbose_name='Source du taux')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_from', to='currencies.currency', verbose_name='Devise source')),
                ('to_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_rates_to', to='currencies.currency', verbose_name='Devise cible')),
            ],
            options={
                'verbose_name': 'Taux de change',
                'verbose_name_plural': 'Taux de change',
                'db_table': 'currencies_exchange_rate',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['from_currency', 'to_currency', 'date'], name='currencies__from_cu_1d93a5_idx'), models.Index(fields=['date'], name='currencies__date_ce93f8_idx'), models.Index(fields=['is_active'], name='currencies__is_acti_275477_idx')],
                'unique_together': {('from_currency', 'to_currency', 'date')},
            },
        ),
    ]
