# Generated by Django 6.0.5 on 2026-05-21 23:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JournalEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(help_text='Numéro de la pièce comptable', max_length=50, verbose_name='Référence')),
                ('date', models.DateField(verbose_name="Date de l'opération")),
                ('description', models.TextField(verbose_name='Description')),
                ('is_posted', models.BooleanField(default=False, help_text="Indique si l'écriture est validée et comptabilisée", verbose_name='Comptabilisé')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('source', models.CharField(choices=[('manual', 'Saisie manuelle'), ('api', 'API externe'), ('ai_suggestion', 'Suggestion IA')], default='manual', help_text="Origine de l'écriture comptable", max_length=20, verbose_name='Source')),
                ('is_validated', models.BooleanField(default=True, help_text="L'écriture a été validée par un humain", verbose_name='Validée')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('hash', models.CharField(blank=True, editable=False, help_text="Hash SHA-256 de l'écriture pour immuabilité", max_length=64, null=True, verbose_name='Hash SHA-256')),
                ('previous_hash', models.CharField(blank=True, editable=False, help_text="Hash de l'écriture précédente dans la chaîne", max_length=64, null=True, verbose_name='Hash précédent')),
            ],
            options={
                'verbose_name': 'Écriture comptable',
                'verbose_name_plural': 'Écritures comptables',
                'db_table': 'journal_entries',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JournalLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_type', models.CharField(choices=[('debit', 'Débit'), ('credit', 'Crédit')], max_length=10, verbose_name='Type de ligne')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='Montant')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('reconciled', models.BooleanField(default=False, help_text='Indique si cette ligne a été rapprochée avec une transaction bancaire', verbose_name='Rapprochée')),
                ('reconciled_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de rapprochement')),
            ],
            options={
                'verbose_name': "Ligne d'écriture",
                'verbose_name_plural': "Lignes d'écriture",
                'db_table': 'journal_lines',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Code selon le plan comptable OHADA (ex: 4011)', max_length=10, verbose_name='Code du compte')),
                ('label', models.CharField(max_length=200, verbose_name='Libellé du compte')),
                ('account_type', models.CharField(choices=[('asset', 'Actif'), ('liability', 'Passif'), ('equity', 'Capitaux propres'), ('revenue', 'Produit'), ('expense', 'Charge')], max_length=20, verbose_name='Type de compte')),
                ('account_class', models.IntegerField(choices=[(1, 'Classe 1 - Capitaux propres et emprunts'), (2, 'Classe 2 - Immobilisations'), (3, 'Classe 3 - Stocks'), (4, 'Classe 4 - Tiers'), (5, 'Classe 5 - Trésorerie'), (6, 'Classe 6 - Charges'), (7, 'Classe 7 - Produits'), (8, 'Classe 8 - Engagements hors bilan')], verbose_name='Classe de compte')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accounts', to='organizations.organization', verbose_name='Organisation')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='accounting.account', verbose_name='Compte parent')),
            ],
            options={
                'verbose_name': 'Compte',
                'verbose_name_plural': 'Comptes',
                'db_table': 'accounts',
                'ordering': ['code'],
            },
        ),
    ]
