# Generated by Django 6.0.5 on 2026-05-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrateur'), ('accountant', 'Comptable'), ('viewer', 'Lecteur')], default='viewer', max_length=20),
        ),
    ]
