# Generated by Django 6.0.5 on 2026-05-22 18:51

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_organizationinvitation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackAggregation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(max_length=50)),
                ('account_code', models.CharField(max_length=20)),
                ('total_feedbacks', models.IntegerField(default=0)),
                ('average_rating', models.FloatField(default=0.0)),
                ('correct_suggestions', models.IntegerField(default=0)),
                ('incorrect_suggestions', models.IntegerField(default=0)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_aggregations', to='organizations.organization')),
            ],
            options={
                'ordering': ['-period_end'],
                'indexes': [models.Index(fields=['organization', 'feedback_type', 'period_end'], name='feedback_fe_organiz_24f059_idx'), models.Index(fields=['account_code', 'period_end'], name='feedback_fe_account_862e0f_idx')],
                'unique_together': {('organization', 'feedback_type', 'account_code', 'period_start', 'period_end')},
            },
        ),
        migrations.CreateModel(
            name='UserFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feedback_type', models.CharField(choices=[('account_suggestion', 'Suggestion de compte'), ('magic_match', 'Magic Match'), ('document_analysis', 'Analyse de document'), ('journal_entry', "Suggestion d'écriture")], max_length=50)),
                ('rating', models.IntegerField(choices=[(1, 'Très mauvais'), (2, 'Mauvais'), (3, 'Neutre'), (4, 'Bon'), (5, 'Excellent')])),
                ('suggested_account_code', models.CharField(blank=True, max_length=20, null=True)),
                ('suggested_account_label', models.CharField(blank=True, max_length=200, null=True)),
                ('actual_account_code', models.CharField(blank=True, max_length=20, null=True)),
                ('actual_account_label', models.CharField(blank=True, max_length=200, null=True)),
                ('transaction_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('transaction_description', models.TextField(blank=True, null=True)),
                ('transaction_date', models.DateField(blank=True, null=True)),
                ('comment', models.TextField(blank=True, null=True)),
                ('improvement_suggestion', models.TextField(blank=True, null=True)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='organizations.organization')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['organization', 'feedback_type', 'rating'], name='feedback_us_organiz_94ca86_idx'), models.Index(fields=['suggested_account_code', 'actual_account_code'], name='feedback_us_suggest_e56482_idx'), models.Index(fields=['created_at'], name='feedback_us_created_f91a6e_idx')],
            },
        ),
    ]
