# Generated by Django 6.0.5 on 2026-05-22 10:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom du rôle')),
                ('role_type', models.CharField(choices=[('super_admin', 'Super Administrateur'), ('org_admin', 'Administrateur Organisation'), ('accountant', 'Comptable'), ('senior_accountant', 'Comptable Senior'), ('auditor', 'Auditeur'), ('expert_accountant', 'Expert-Comptable'), ('employee', 'Employé'), ('readonly', 'Lecture seule')], max_length=20, verbose_name='Type de rôle')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('level', models.IntegerField(default=0, help_text='Plus élevé = plus de permissions', verbose_name='Niveau hiérarchique')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roles', to='organizations.organization', verbose_name='Organisation')),
                ('permissions', models.ManyToManyField(blank=True, related_name='custom_roles', to='auth.permission', verbose_name='Permissions')),
            ],
            options={
                'verbose_name': 'Rôle',
                'verbose_name_plural': 'Rôles',
                'db_table': 'permissions_role',
                'ordering': ['level', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expire le')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_roles', to=settings.AUTH_USER_MODEL, verbose_name='Assigné par')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='permissions.role', verbose_name='Rôle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Utilisateur')),
            ],
            options={
                'verbose_name': 'Rôle utilisateur',
                'verbose_name_plural': 'Rôles utilisateurs',
                'db_table': 'permissions_user_role',
            },
        ),
        migrations.CreateModel(
            name='PermissionCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_key', models.CharField(max_length=255, verbose_name='Clé de permission')),
                ('has_permission', models.BooleanField(verbose_name='Permission accordée')),
                ('expires_at', models.DateTimeField(verbose_name='Expire le')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_cache', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cache de permission',
                'verbose_name_plural': 'Caches de permissions',
                'db_table': 'permissions_cache',
                'indexes': [models.Index(fields=['user', 'expires_at'], name='permissions_user_id_f0ec26_idx'), models.Index(fields=['expires_at'], name='permissions_expires_8a2efe_idx')],
                'unique_together': {('user', 'permission_key')},
            },
        ),
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la policy')),
                ('policy_type', models.CharField(choices=[('resource_access', 'Accès ressource'), ('field_access', 'Accès champ'), ('action_permission', 'Permission action'), ('time_restriction', 'Restriction temporelle'), ('data_filter', 'Filtrage données'), ('workflow_approval', 'Validation workflow')], max_length=20, verbose_name='Type de policy')),
                ('effect', models.CharField(choices=[('allow', 'Autoriser'), ('deny', 'Refuser'), ('conditional', 'Conditionnel')], max_length=20, verbose_name='Effet')),
                ('resource_type', models.CharField(help_text='ex: accounting.JournalEntry, invoicing.Invoice', max_length=50, verbose_name='Type de ressource')),
                ('resource_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID de la ressource')),
                ('conditions', models.JSONField(default=dict, help_text="Conditions d'application de la policy", verbose_name='Conditions')),
                ('actions', models.JSONField(default=list, help_text='Liste des actions concernées', verbose_name='Actions')),
                ('fields', models.JSONField(default=list, help_text='Liste des champs concernés', verbose_name='Champs')),
                ('priority', models.IntegerField(default=100, verbose_name='Priorité')),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policies', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policies', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': 'Policy',
                'verbose_name_plural': 'Policies',
                'db_table': 'permissions_policy',
                'ordering': ['-priority', 'name'],
                'indexes': [models.Index(fields=['organization', 'resource_type'], name='permissions_organiz_e5c72a_idx'), models.Index(fields=['policy_type', 'is_active'], name='permissions_policy__f307eb_idx'), models.Index(fields=['priority'], name='permissions_priorit_f080b5_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['organization', 'role_type'], name='permissions_organiz_62fff9_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['level'], name='permissions_level_08c3c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='role',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='permissions_user_id_0622a8_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='permissions_role_id_ddd10d_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['expires_at'], name='permissions_expires_0194c8_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
