# Generated by Django 6.0.5 on 2026-05-22 10:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('currencies', '__first__'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IntegrationSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la source')),
                ('source_type', models.CharField(choices=[('excel', 'Excel/CSV'), ('odoo', 'Odoo ERP'), ('sage', 'Sage Comptabilité'), ('momo', 'Mobile Money'), ('bank_api', 'API Bancaire'), ('csv_bank', 'CSV Bancaire'), ('quickbooks', 'QuickBooks'), ('custom_api', 'API Personnalisée')], max_length=20, verbose_name='Type de source')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('config', models.JSONField(default=dict, help_text='Configuration spécifique à la source (format JSON)', verbose_name='Configuration')),
                ('endpoint_url', models.URLField(blank=True, help_text='URL pour les sources API', verbose_name='URL endpoint')),
                ('api_key', models.CharField(blank=True, help_text='Clé API pour les sources externes', max_length=255, verbose_name='Clé API')),
                ('status', models.CharField(choices=[('active', 'Actif'), ('inactive', 'Inactif'), ('error', 'Erreur'), ('syncing', 'Synchronisation')], default='active', max_length=20, verbose_name='Statut')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='Dernière synchronisation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_integration_sources', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='integration_sources', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Source d'intégration",
                'verbose_name_plural': "Sources d'intégration",
                'db_table': 'integrations_integration_source',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='RawIngestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_fingerprint', models.CharField(help_text='Hash SHA-256 du payload brut pour éviter les doublons', max_length=64, unique=True, verbose_name='Fingerprint source')),
                ('payload_type', models.CharField(choices=[('json', 'JSON'), ('file', 'Fichier'), ('text', 'Texte')], max_length=20, verbose_name='Type de payload')),
                ('file', models.FileField(blank=True, null=True, upload_to='integrations/raw/%Y/%m/', verbose_name='Fichier')),
                ('file_name', models.CharField(blank=True, max_length=255, verbose_name='Nom du fichier')),
                ('file_size', models.PositiveIntegerField(blank=True, null=True, verbose_name='Taille du fichier (octets)')),
                ('raw_data', models.JSONField(blank=True, help_text='Payload JSON brut', null=True, verbose_name='Données brutes')),
                ('raw_text', models.TextField(blank=True, verbose_name='Texte brut')),
                ('processing_status', models.CharField(choices=[('pending', 'En attente'), ('processing', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué'), ('validated', 'Validé'), ('rejected', 'Rejeté')], default='pending', max_length=20, verbose_name='Statut de traitement')),
                ('processing_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Début du traitement')),
                ('processing_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Fin du traitement')),
                ('total_records', models.PositiveIntegerField(default=0, verbose_name='Total des enregistrements')),
                ('processed_records', models.PositiveIntegerField(default=0, verbose_name='Enregistrements traités')),
                ('failed_records', models.PositiveIntegerField(default=0, verbose_name='Enregistrements échoués')),
                ('error_log', models.JSONField(default=list, help_text='Liste des erreurs de traitement', verbose_name='Log des erreurs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_raw_ingestions', to=settings.AUTH_USER_MODEL, verbose_name='Créé par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_ingestions', to='organizations.organization', verbose_name='Organisation')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_ingestions', to='integrations.integrationsource', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Ingestion brute',
                'verbose_name_plural': 'Ingestions brutes',
                'db_table': 'integrations_raw_ingestion',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NormalizedTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_label', models.TextField(help_text="Libellé tel qu'il apparaît dans la source", verbose_name='Libellé original')),
                ('original_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Montant original')),
                ('original_date', models.DateField(verbose_name='Date originale')),
                ('normalized_label', models.TextField(blank=True, help_text='Libellé après nettoyage et normalisation', verbose_name='Libellé normalisé')),
                ('normalized_amount', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Montant normalisé')),
                ('normalized_date', models.DateField(verbose_name='Date normalisée')),
                ('debit_confidence_score', models.IntegerField(blank=True, null=True, verbose_name='Score de confiance débit (0-100)')),
                ('credit_confidence_score', models.IntegerField(blank=True, null=True, verbose_name='Score de confiance crédit (0-100)')),
                ('validation_status', models.CharField(choices=[('pending', 'En attente'), ('validated', 'Validé'), ('rejected', 'Rejeté'), ('processed', 'Traité')], default='pending', max_length=20, verbose_name='Statut de validation')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation')),
                ('validation_notes', models.TextField(blank=True, verbose_name='Notes de validation')),
                ('ai_suggestions', models.JSONField(default=dict, help_text="Suggestions détaillées de l'IA", verbose_name='Suggestions IA')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('currency', models.ForeignKey(blank=True, help_text='Devise de la transaction (auto-détectée ou spécifiée)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='normalized_transactions', to='currencies.currency', verbose_name='Devise')),
                ('journal_entry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_transaction', to='accounting.journalentry', verbose_name='Écriture comptable générée')),
                ('suggested_credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_credit_transactions', to='accounting.account', verbose_name='Compte crédit suggéré')),
                ('suggested_debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_debit_transactions', to='accounting.account', verbose_name='Compte débit suggéré')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Validé par')),
                ('validated_credit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_credit_transactions', to='accounting.account', verbose_name='Compte crédit validé')),
                ('validated_debit_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_debit_transactions', to='accounting.account', verbose_name='Compte débit validé')),
                ('raw_ingestion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_transactions', to='integrations.rawingestion', verbose_name='Ingestion brute')),
            ],
            options={
                'verbose_name': 'Transaction normalisée',
                'verbose_name_plural': 'Transactions normalisées',
                'db_table': 'integrations_normalized_transaction',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='integrationsource',
            index=models.Index(fields=['organization', 'source_type'], name='integration_organiz_2aa19f_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsource',
            index=models.Index(fields=['status'], name='integration_status_1b591d_idx'),
        ),
        migrations.AddIndex(
            model_name='integrationsource',
            index=models.Index(fields=['last_sync_at'], name='integration_last_sy_983f8f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='integrationsource',
            unique_together={('organization', 'name')},
        ),
        migrations.AddIndex(
            model_name='rawingestion',
            index=models.Index(fields=['organization', 'processing_status'], name='integration_organiz_2dac13_idx'),
        ),
        migrations.AddIndex(
            model_name='rawingestion',
            index=models.Index(fields=['source', 'processing_status'], name='integration_source__758208_idx'),
        ),
        migrations.AddIndex(
            model_name='rawingestion',
            index=models.Index(fields=['source_fingerprint'], name='integration_source__bba7e3_idx'),
        ),
        migrations.AddIndex(
            model_name='rawingestion',
            index=models.Index(fields=['created_at'], name='integration_created_6edda0_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedtransaction',
            index=models.Index(fields=['raw_ingestion', 'validation_status'], name='integration_raw_ing_e4ffb1_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedtransaction',
            index=models.Index(fields=['validation_status'], name='integration_validat_69cc69_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedtransaction',
            index=models.Index(fields=['normalized_date'], name='integration_normali_c9a4c5_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedtransaction',
            index=models.Index(fields=['currency'], name='integration_currenc_0a4973_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedtransaction',
            index=models.Index(fields=['suggested_debit_account'], name='integration_suggest_eee791_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedtransaction',
            index=models.Index(fields=['suggested_credit_account'], name='integration_suggest_5a3c14_idx'),
        ),
        migrations.AddIndex(
            model_name='normalizedtransaction',
            index=models.Index(fields=['journal_entry'], name='integration_journal_c06ebd_idx'),
        ),
    ]
