# Generated by Django 6.0.5 on 2026-05-21 23:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date de transaction')),
                ('description', models.CharField(help_text='Description de la transaction bancaire', max_length=500, verbose_name='Description')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Montant')),
                ('transaction_type', models.CharField(choices=[('credit', 'Crédit'), ('debit', 'Débit')], default='credit', max_length=10, verbose_name='Type de transaction')),
                ('reference', models.CharField(help_text='Référence unique de la transaction', max_length=100, unique=True, verbose_name='Référence')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('matched', 'Rapprochée'), ('flagged', 'Signalée'), ('ignored', 'Ignorée')], default='pending', max_length=20, verbose_name='Statut')),
                ('confidence_score', models.IntegerField(default=0, help_text='Score de confiance du matching automatique (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Score de confiance')),
                ('notes', models.TextField(blank=True, help_text='Notes sur la réconciliation', verbose_name='Notes')),
                ('import_batch_id', models.CharField(blank=True, help_text="Identifiant du lot d'import pour traçabilité", max_length=50, verbose_name="ID de lot d'import")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de mise à jour')),
                ('matched_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de rapprochement')),
            ],
            options={
                'verbose_name': 'Transaction bancaire',
                'verbose_name_plural': 'Transactions bancaires',
                'db_table': 'reconciliation_bank_transaction',
                'ordering': ['-date', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.CharField(max_length=50, unique=True, verbose_name='ID du lot')),
                ('filename', models.CharField(max_length=255, verbose_name='Nom du fichier')),
                ('status', models.CharField(choices=[('pending', 'En cours'), ('completed', 'Terminé'), ('failed', 'Échoué')], default='pending', max_length=20, verbose_name='Statut')),
                ('total_rows', models.IntegerField(default=0, verbose_name='Total lignes')),
                ('imported_rows', models.IntegerField(default=0, verbose_name='Lignes importées')),
                ('failed_rows', models.IntegerField(default=0, verbose_name='Lignes échouées')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': "Lot d'import",
                'verbose_name_plural': "Lots d'import",
                'db_table': 'reconciliation_import_batch',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la règle')),
                ('rule_type', models.CharField(choices=[('amount_exact', 'Montant exact'), ('amount_range', 'Plage de montant'), ('description_contains', 'Description contient'), ('reference_contains', 'Référence contient'), ('date_range', 'Plage de dates')], max_length=20, verbose_name='Type de règle')),
                ('parameters', models.JSONField(default=dict, help_text='Paramètres de la règle au format JSON', verbose_name='Paramètres')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('priority', models.IntegerField(default=100, help_text='Priorité de la règle (plus petit = plus prioritaire)', verbose_name='Priorité')),
                ('confidence_boost', models.IntegerField(default=10, help_text='Bonus de confiance ajouté si la règle correspond', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(50)], verbose_name='Bonus de confiance')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Règle de réconciliation',
                'verbose_name_plural': 'Règles de réconciliation',
                'db_table': 'reconciliation_rule',
                'ordering': ['priority', 'name'],
            },
        ),
    ]
