# Generated by Django 6.0.5 on 2026-05-21 23:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0002_initial'),
        ('organizations', '0001_initial'),
        ('reconciliation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='imported_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Importé par'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='journal_line',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transaction', to='accounting.journalline', verbose_name="Ligne d'écriture associée"),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='matched_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_transactions', to=settings.AUTH_USER_MODEL, verbose_name='Rapproché par'),
        ),
        migrations.AddField(
            model_name='banktransaction',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transactions', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Importé par'),
        ),
        migrations.AddField(
            model_name='importbatch',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='import_batches', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation_rules', to='organizations.organization', verbose_name='Organisation'),
        ),
        migrations.AddField(
            model_name='reconciliationrule',
            name='target_account',
            field=models.ForeignKey(help_text='Compte vers lequel matcher les transactions', on_delete=django.db.models.deletion.CASCADE, to='accounting.account', verbose_name='Compte cible'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['organization', 'status'], name='reconciliat_organiz_3288b3_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['organization', 'date'], name='reconciliat_organiz_f59b3e_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['status', 'date'], name='reconciliat_status_92cf8e_idx'),
        ),
        migrations.AddIndex(
            model_name='banktransaction',
            index=models.Index(fields=['reference'], name='reconciliat_referen_1cc9c2_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='reconciliationrule',
            unique_together={('organization', 'name')},
        ),
    ]
