# Generated by Django 6.0.5 on 2026-05-22 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconciliation', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='banktransaction',
            name='receipt_image',
            field=models.ImageField(blank=True, help_text="Capture d'écran du reçu Mobile Money", null=True, upload_to='receipts/', verbose_name='Image du reçu'),
        ),
    ]
