# Generated by Django 6.0.5 on 2026-05-22 17:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('role', models.CharField(choices=[('admin', 'Administrateur'), ('accountant', 'Comptable'), ('viewer', 'Lecteur')], default='viewer', max_length=20, verbose_name='Rôle')),
                ('token', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name="Token d'invitation")),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Acceptée')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'acceptation")),
                ('expires_at', models.DateTimeField(verbose_name="Date d'expiration")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accepted_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Acceptée par')),
                ('invited_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_invitations', to=settings.AUTH_USER_MODEL, verbose_name='Invité par')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='organizations.organization', verbose_name='Organisation')),
            ],
            options={
                'verbose_name': "Invitation d'organisation",
                'verbose_name_plural': "Invitations d'organisation",
                'db_table': 'organizations_invitation',
                'ordering': ['-created_at'],
                'unique_together': {('email', 'organization', 'is_accepted')},
            },
        ),
    ]
